---
kind: pipeline
name: default

# Disable default clone
clone:
  disable: true

steps:
  # This clone step doesn't use "root" user
  - name: clone
    image: thehiveproject/drone-git
    settings:
      submodule_override:
        - ScalliGraph: https://github.com/TheHive-Project/ScalliGraph.git


  # Restore cache of downloaded dependencies
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - .sbt
        - .ivy2
    volumes: [{name: cache, path: /cache}]

  # Run project tests
  - name: run-tests
    image: thehiveproject/drone-scala-node
    commands:
      - sbt -Duser.home=$PWD +test:compile +test

  # Save external libraries in cache
  - name: save-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - .sbt
        - .ivy2
    volumes: [{name: cache, path: /cache}]

volumes:
  - name: cache
    host:
      path: /opt/drone/cache
